# There may be some repetitions here！
# install.packages("fpp2")
library(fpp2)
library(dplyr)
library(tidyr)
library(zoo)
# install.packages("ggfortify")
library(ggfortify)
library(gridExtra)
library(VIM)
library(mice)
library(knitr)
library(ggplot2)
library(dplyr)
library(xts)
library(RColorBrewer)
library(rworldmap)
library(ggthemes)
library(rgdal)
library(tidyverse)
library(tseries)
library(forecast)
# install.packages("dygraphs")
library(dygraphs)
#Visualisation 
library(corrplot)
library(viridis)
library(knitr)
library(ggthemes)
library(corrplot)
#library(ggfortify)
library(reshape2)
library(gridExtra)
library(lubridate)
library(caret)
library(psych)
library(reshape2)

library(dplyr)
library(lubridate)
library(ggplot2)
library(forecast)
library(DMwR)
library(nnet)
library(reshape2)
# install.packages(c("FactoMineR", "factoextra"))
library("FactoMineR")
library("factoextra")
library(naniar)
library(Hmisc)
